### ISSUE TITLE
zuul signed-off-by test giving false positives

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#120]
Was looking at pr BonnyCI/hoist#139

and saw that Travis failed, on a signed-off-by, but Zuul did not fail that: http://logs.bonnyci.com/check_github/BonnyCI/hoist/139/1486947519.79/hoist-checks/console.html#_2017-02-13_00_58_59_562365

Something appears wrong with our test.

**Comment by ConsoleCatzirl** [comment]
This looks like it ran the test against the master branch instead of against the proposed change: http://logs.bonnyci.com/check_github/BonnyCI/hoist/139/1486947519.79/hoist-checks/console.html#_2017-02-13_00_58_49_994325

This was likely caused by an issue with the zuul merger. I will pick up my ancient zuul-cloner change to abort rather than fall back to the master branch: https://review.openstack.org/227955

**Comment by omgjlk** [comment]
This will be fixed in v3, because in v3 the merger pushes code to the node, rather than having the node pull from a/the merger.
