### ISSUE TITLE
Decide on production account, project, and network strategy

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#130]
With our new cloud, as we have the power to create new accounts, projects, and networks, we need a strategy for deploying our control plane and utilizing capacity for node pool nodes. We should use a design that keeps attack surfaces small, balanced with keeping complexity low.

Design proposals should go to Lore.

**Comment by gandelman-a** [comment]
So I've been looking into the network topology.  We should be able to use security groups within the control plane to limit traffic to only required ports. I'd like for us to avoid a flat-network topology we have with the current setup and have nodepool slaves in their own tenant and private network, but I'm having trouble with the bluebox cloud while attempting to create L3 connectivity between the control-plane and nodepool networks. The other option is to have nodepool spin up nodes in a private tenant but with floating IPs, but that seems like a waste.  May need to file a ticket with BB folks to see what is limited in the API since it doesn't allow me to attach ports from a shared network on tenantA onto a router of tenantB.

**Comment by omgjlk** [comment]
We won't be able to plug ports on the default router, but we may be able to make our own router and plug ports on that. Have you tried that?

**Comment by gandelman-a** [comment]
Yep, I'm using a new router on a tenant.  In fact, I dont think there is a default router. 

Anyway, I've put in a ticket with BB and they let me know that attaching a shared network from tenantB to a new router on tenantA is only possible by admin, and they would need to it manually for us... which would break automation. So barring that, we could go the floating IP route and be stingy with floating IPs allocated to developer accounts (only allow them a single IP and require them to use a jump host).  OR we could directly attach ports from a shared nodepool network to zuul and nodepool nodes to allow L2 connectivity to slaves in the other tenant booted on the same network.

**Comment by SpamapS** [comment]
Can we have ipv6 floating ips?

**Comment by omgjlk** [comment]
I'm not sure what the ipv6 capabilities are in a blue mix private cloud, but probably not what we need.

Adam and I chatted on iRC and he's trying another approach:

With Tenant A user that has `cloud_admin` role in Tenant A, create two private networks, one of which is shared. Also create a router, and plug both networks into the router. Then Tenant B can boot instances with ports on the shared network from tenant A. Security groups limit the cross-talk.

**Comment by missaugustina** [comment]
Looks like @gandelman-a is working on this so I've assigned it to him and removed the help wanted label

**Comment by gandelman-a** [comment]
Design spec was merged, the implementation is being worked on here https://github.com/BonnyCI/hoist/pull/168 by @eggshell

**Comment by missaugustina** [comment]
Looks like the implementation has merged, closing this out.
