### ISSUE TITLE
Nodepool builder is generating ~1GB of logs per day

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#97]
Disk space monitoring on Nodepool had triggered alerts and upon further analysis, we found Nodepool builder is generating about 1 GB of logs per day. We need to investigate if this is normal activity or if something else is going on. We are a pretty small project and that seems like a lot.

**Comment by rattboi** [comment]
Looks like there are two reasons why nodepool builder logs are filling up so quickly.

1. We have two logs, normal + debug. They actually are identical, so that's double the logs right there. Fixing this would get us to ~500MB/day. 
2. There is an attempt to build an ubuntu-xenial image that fails every 10-45 seconds. This generates 240kb (x2 because of above) of logs. 

I think the solution is two-fold. 
- [x] We should figure out why dib is failing, and fix that.
- [ ] We should implement logrotate in general for nodepool, as we did for zuul. Without it, we would fill up over time regardless of the dib nodepool-builder failure.

**Comment by rattboi** [comment]
bonnyci/hoist#80 will give us the logrotate for nodepool. Once it's merged, we can close this.

**Comment by missaugustina** [comment]
Looks like it merged, is this issue resolved?

**Comment by missaugustina** [comment]
What's the status of this issue?
